spring.application.name=The-Cheff

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/pdv
spring.datasource.username=postgres
spring.datasource.password=205326

# JPA
spring.jpa.hibernate.ddl-auto=update

# SQL COMMANDS
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.type=trace

api.security.token.secret=${JWT_SECRET:my-secret-key}